name: shorebird_code_push_example
description: An example demonstrating how to use the shorebird_code_push package
publish_to: 'none'

version: 1.0.0+16

environment:
  sdk: '>=3.0.5 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  shorebird_code_push:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
